# Generated by Django 3.1.4 on 2020-12-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201225_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='django-summernote/2020-12-25'),
        ),
    ]
