# Generated by Django 3.1.4 on 2020-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201226_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='django-summernote/2020-12'),
        ),
    ]
